name: .NET Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --verbosity normal
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Binaries ${{ matrix.os }}
          path: ${{ fromJSON(steps.upload.outputs.result).file }}
