name: .NET Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Publish
        run: dotnet publish --verbosity normal
      - name: Upload build artifacts (linux)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: Binaries ${{ matrix.os }}
          path: ‎Geometry_Smash/bin/Release/net8.0/linux-x64/Geometry_Smash
      - name: Upload build artifacts (windows)
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: Binaries ${{ matrix.os }}
          path: ‎Geometry_Smash/bin/Release/net8.0/win-x64/Geometry_Smash.exe
